### ISSUE TITLE
[FEATURE] Ability to run the script from IBM Cloud Shell

### ISSUE THREAD

**Issue by bpradipt** [ocp-power-automation/openshift-install-power#115]
**Is your feature request related to a problem? Please describe.**
I would like to deploy OpenShift on PowerVS using IBM Cloud shell which comes preconfigured with necessary tools and utilities

https://cloud.ibm.com/docs/cloud-shell?topic=cloud-shell-shell-ui

**Describe the solution you'd like**
IBM Cloud Shell is a temporary environment. So tfstate and other details need to be stored in a persistent storage like IBM Cloud object store or Git.

The solution should handle this aspect

**Comment by yussufsh** [comment]
IMO it is not a good idea to deploy from IBM Cloud shell because the deployment configurations contains sensitive and required files such as ssh keys, pull-secret and Terraform state file. These files are also needed for destroy purpose later. Maintaining the same session is difficult due to network disconnections, closing the browser tabs, etc.

Supporting remote backend for state is a Terraform feature and need to be implemented in the parent project. Also I do not think IBM Cloud Object Storage or Git is supported. Even it will need additional mechanism to manage endpoints and authenticate these services for storing the sensitive state file for supported backends.

**Comment by dpkshetty** [comment]
I would want to see a feature where I can start the create step, answer all questions and I should be able to disconnect and close my laptop/shell. I know one way is to use screen linux cmd from a lab server but not always lab server (always-on) is available for everyone in order to use screen or equivalent cmd.

**Comment by yussufsh** [comment]
> 
> I would want to see a feature where I can start the create step, answer all questions and I should be able to disconnect and close my laptop/shell. I know one way is to use screen linux cmd from a lab server but not always lab server (always-on) is available for everyone in order to use screen or equivalent cmd.

I am sure this is not possible since Terraform process needs to be running always in the background. The script support re-running create and re-start from the last point when the session was disconnected or teraform process was ended.
